packages:
  - apps/**
  - packages/**
  - tooling/**
  - supabase
  - e2e

catalog:
  '@tailwindcss/postcss': 4.1.18
  '@tanstack/react-query': 5.90.12
  '@trpc/client': 11.8.0
  '@trpc/react-query': 11.8.0
  '@trpc/tanstack-react-query': 11.8.0
  '@trpc/server': ^11.8.0
  '@turbo/gen': ^2.6.3
  eslint: ^9.39.2
  lucide-react: ^0.561.0
  prettier: ^3.6.2
  superjson: 2.2.6
  tailwindcss: 4.1.18
  typescript: ^5.9.3
  zod: ^4.2.1

catalogs:
  react:
    '@types/react': ^19.2.7
    '@types/react-dom': ^19.2.3
    next: ^15.5.9
    react: ^19.2.3
    react-dom: ^19.2.3
  native:
    '@types/react': ~19.1.0
    '@invertase/react-native-apple-authentication': ^2.5.0
    '@react-native-google-signin/google-signin': ^16.1.1
    expo: ~54.0.30
    expo-linking: ~8.0.11
    lucide-react-native: ^0.562.0
    react: 19.1.0
    react-dom: 19.1.0
    react-native: 0.81.5
    react-native-css: ^3.0.1
    nativewind: 5.0.0-preview.2


nodeLinker: hoisted

onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - bufferutil
  - core-js-pure
  - esbuild
  - sharp
  - supabase
  - unrs-resolver
  - utf-8-validate
